@baseUrl = http://localhost:3000

# list notifications
GET {{baseUrl}}/notifications
Content-Type: application/json

###
#create notifications
POST {{baseUrl}}/notifications
Content-Type: application/json

{
  "content": "Novo pedido de amizade!",
  "category": "social",
  "recipientId": "{{$guid}}"
}

###
